"""Generate manuscript Tables 1 and 2 from the saved reduction products.

Runs no experiment reduction of its own: it reads the CSVs written by
`exp_analysis.py`, `dimensionless_analysis.py` and `uncertainty_analysis.py`
and emits the two manuscript tables in both machine- and manuscript-readable
form. Re-run after any change to the reduction so the tables cannot drift from
the data.

Inputs   (all in this directory)
  dimensionless_groups.csv     per-run dimensionless quantities
  uncertainty_per_run.csv      Monte Carlo standard deviations per run
  eigenvalue_verification.csv  slow-mode eigenvalues, heating and cooling
  delivered_power_check.csv    per-run delivered-power factors, K bracket
  steady_state_metrics.csv     steady means and t90 values

Outputs  (all in this directory)
  table1_campaign_envelope.csv / .md
  table2_identified_constants.csv / .md

Definitions follow Section 3.2 of the manuscript:
  Tw_bar = 0.248 T8 + 0.365 T12 + 0.387 T11,  eps = (T3-Tamb)/(Tw_bar-Tamb),
  NTU = -ln(1-eps),  I_vol = T12 - T8.
Eigenvalue identification follows Section 4.7: lam = (eps*mdot*cp + K)/C, so a
regression of lam on x = eps*mdot*cp has slope 1/C and intercept K/C.
"""
import os
import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
P = lambda f: os.path.join(HERE, f)
RNG = np.random.default_rng(7)
NMC = 20000
SIG_TC = 2.2 / 2.0          # type-N class tolerance, treated as 2 sigma


def ci(v, lo=2.5, hi=97.5):
    return np.percentile(v, lo), np.percentile(v, hi)


def fmt(v, c, nd=3):
    return f"{v:.{nd}f} [{c[0]:.{nd}f}, {c[1]:.{nd}f}]"


# --------------------------------------------------------------------------
# Table 1 - campaign and dimensionless envelope
# --------------------------------------------------------------------------
def table1():
    d = pd.read_csv(P("dimensionless_groups.csv"))
    u = pd.read_csv(P("uncertainty_per_run.csv"))
    m = pd.read_csv(P("steady_state_metrics.csv"))[["ID", "eta_gas", "eta_del"]]
    t = d.merge(u, on="ID").merge(m, on="ID")

    out = pd.DataFrame({
        "run": t.ID,
        "G0_kW_m2": t.Io_kWm2.round(0).astype(int),
        "q_sLmin": t.q_slpm.round(2),
        "mdot_g_s": t.mdot_gs.round(4),
        "Re": t.Re.round(1),
        "Re_sd": t.Re_sd.round(1),
        "Gz_L": t.Gz_L.round(3),
        "Tw_bar_K": t.Tw_K.round(1),
        "T3_K": t.T3_K.round(1),
        "eps": t.eps.round(3),
        "eps_sd": t.eps_sd.round(3),
        "NTU": t.NTU.round(3),
        "NTU_sd": t.NTU_sd.round(3),
        "Nu_app": t.Nu.round(4),
        "Nu_app_sd": t.Nu_sd.round(4),
        "Lambda_107": t.LTNE107.round(4),
        "I_vol_K": t.I_vol_wall.round(1),
        "PR_del_kJ_kg": t.PR_del_kJkg.round(0),
        "eta_gas": t.eta_gas.round(3),
        "eta_del": t.eta_del.round(3),
    }).sort_values(["G0_kW_m2", "q_sLmin"], ascending=[False, True])
    out.to_csv(P("table1_campaign_envelope.csv"), index=False)

    cols = ["run", "G0_kW_m2", "q_sLmin", "Re", "Gz_L", "Tw_bar_K", "T3_K",
            "eps", "NTU", "Nu_app", "Lambda_107", "I_vol_K", "eta_del"]
    hdr = ["Run", "G0 [kW m-2]", "q [sL min-1]", "Re", "Gz_L", "Tw_bar [K]",
           "T3 [K]", "eps", "NTU", "Nu_app", "L_107", "I_vol [K]", "eta_del"]
    md = ["**Table 1.** Experimental campaign and dimensionless envelope. "
          "Generated by `make_tables.py`.", "",
          "| " + " | ".join(hdr) + " |",
          "|" + "|".join(["---"] * len(hdr)) + "|"]
    for _, r in out.iterrows():
        md.append("| " + " | ".join(str(r[c]) for c in cols) + " |")
    md += ["", f"Envelope: Re {out.Re.min():.0f}-{out.Re.max():.0f}, "
               f"eps {out.eps.min():.3f}-{out.eps.max():.3f}, "
               f"NTU {out.NTU.min():.2f}-{out.NTU.max():.2f}, "
               f"Nu_app {out.Nu_app.min():.3f}-{out.Nu_app.max():.3f}."]
    open(P("table1_campaign_envelope.md"), "w").write("\n".join(md) + "\n")
    return out


# --------------------------------------------------------------------------
# Table 2 - identified constants
# --------------------------------------------------------------------------
def _powerlaw_mc(re, nu, re_sd, nu_sd):
    a, b = [], []
    for _ in range(NMC):
        r = RNG.normal(re, re_sd)
        n = RNG.normal(nu, nu_sd)
        ok = (r > 0) & (n > 0)
        s, i = np.polyfit(np.log10(r[ok]), np.log10(n[ok]), 1)
        b.append(s); a.append(10 ** i)
    return np.array(a), np.array(b)


def _linear_mc(x, y, x_sd, y_sd):
    s, i = [], []
    for _ in range(NMC):
        sl, ic = np.polyfit(RNG.normal(x, x_sd), RNG.normal(y, y_sd), 1)
        s.append(sl); i.append(ic)
    return np.array(i), np.array(s)


def eps_star(q, ivol, eps):
    """Inversion threshold, manuscript convention (Section 4.4).

    Regress the inversion indicator on flow to locate the zero crossing q*,
    then evaluate the effectiveness regression at q*. Using the regressions
    rather than interpolating between the two bracketing runs uses all five
    points of a group and is what the reported eps* values are built on.
    """
    s, i = np.polyfit(q, ivol, 1)
    qs = -i / s
    se, ie = np.polyfit(q, eps, 1)
    return qs, se * qs + ie


def _crossing_in_eps(eps, ivol):
    """Alternative: interpolate the indicator directly against eps."""
    o = np.argsort(eps)
    e, v = np.asarray(eps)[o], np.asarray(ivol)[o]
    k = np.where(np.diff(np.sign(v)) != 0)[0]
    if len(k) == 0:
        return np.nan
    j = k[0]
    return e[j] + (e[j + 1] - e[j]) * (-v[j]) / (v[j + 1] - v[j])


def _r2(x, y, deg=1):
    p = np.polyfit(x, y, deg)
    r = y - np.polyval(p, x)
    return 1 - r.dot(r) / ((y - y.mean()) ** 2).sum()


def table2():
    """Manuscript Table 2.

    The authoritative values are the Monte Carlo constants written by
    `uncertainty_analysis.py` to `identified_constants_mc.csv`; those are the
    numbers quoted in the text. Where this script can identify the same
    constant independently from the reduction products it does so and reports
    it as a cross-check, so any drift between the two routes is visible in the
    table rather than hidden.
    """
    d = pd.read_csv(P("dimensionless_groups.csv"))
    u = pd.read_csv(P("uncertainty_per_run.csv"))
    t = d.merge(u, on="ID")
    ev = pd.read_csv(P("eigenvalue_verification.csv"))
    dp = pd.read_csv(P("delivered_power_check.csv"))
    mc = pd.read_csv(P("identified_constants_mc.csv"))
    mc = mc[~mc.quantity.str.contains("cooling\\+heating")]
    mcv = {r.quantity: r for _, r in mc.iterrows()}

    # ---- independent cross-checks ---------------------------------------
    chk = {}
    a, b = _powerlaw_mc(t.Re.values, t.Nu.values, t.Re_sd.values, t.Nu_sd.values)
    chk["Nu_app prefactor a  (Nu = a Re^b)"] = f"{a.mean():.2e}"
    chk["Nu_app exponent b"] = f"{b.mean():.3f}"
    r2_nu = _r2(np.log10(t.Re.values), np.log10(t.Nu.values))
    for g, gg in t.groupby("Io_kWm2"):
        qs, e = eps_star(gg.q_slpm.values, gg.I_vol_wall.values, gg.eps.values)
        chk[f"eps* at {g:.0f} kW/m2"] = f"{e:.3f} (q* = {qs:.2f} sL/min)"
    for phase, label in (("cool", "cooling"), ("heat", "heating")):
        e = ev[ev.phase == phase]
        sl, ic = np.polyfit(e.x.values, e.lam.values, 1)
        chk[f"C_eff from {label} [J/K]"] = f"{1 / sl:.0f}"
        chk[f"K_loss from {label} [W/K]"] = f"{ic / sl:.3f}"

    rows = []
    notes = {
        "Nu_app prefactor a  (Nu = a Re^b)": f"log-log r2 = {r2_nu:.3f}, n = {len(t)}",
        "Nu_app exponent b": f"n = {len(t)}",
    }
    for _, r in mc.iterrows():
        q = r.quantity
        val = (f"{r.value:.2e}" if abs(r.value) < 1e-2 else
               f"{r.value:.0f}" if abs(r.value) > 50 else f"{r.value:.3f}")
        if np.isnan(r.ci_lo):
            interval = "-"
        elif abs(r.value) < 1e-2:
            interval = f"[{r.ci_lo:.2e}, {r.ci_hi:.2e}]"
        elif abs(r.value) > 50:
            interval = f"[{r.ci_lo:.0f}, {r.ci_hi:.0f}]"
        else:
            interval = f"[{r.ci_lo:.3f}, {r.ci_hi:.3f}]"
        rows.append((q, val, interval, notes.get(q, ""), chk.get(q, "-"),
                     "identified_constants_mc.csv"))

    # ---- deep-station nonequilibrium (not in the MC summary) -------------
    i0, s0 = _linear_mc(t.Re.values, t.LTNE107.values,
                        t.Re_sd.values, t.L107_sd.values)
    r2 = _r2(t.Re.values, t.LTNE107.values)
    rows.append(("Lambda_107 intercept", f"{i0.mean():.4f}",
                 f"[{ci(i0)[0]:.4f}, {ci(i0)[1]:.4f}]", f"r2 = {r2:.3f}",
                 "-", "dimensionless_groups.csv"))
    rows.append(("Lambda_107 slope [1/Re]", f"{s0.mean():.2e}",
                 f"[{ci(s0)[0]:.2e}, {ci(s0)[1]:.2e}]",
                 "reported as a lower bound", "-", "dimensionless_groups.csv"))

    # ---- delivered-power factors ----------------------------------------
    for g, gg in dp.groupby("Io_kWm2"):
        rows.append((f"delivered-power factor f at {g:.0f} kW/m2",
                     f"{gg['f_K0.096'].mean():.2f}-{gg['f_K0.119'].mean():.2f}",
                     "-", "secant-to-tangent K bracket, systematic band",
                     "-", "delivered_power_check.csv"))

    out = pd.DataFrame(rows, columns=["quantity", "value", "ci_95", "note",
                                      "independent_recheck", "source"])
    out.to_csv(P("table2_identified_constants.csv"), index=False)

    md = ["**Table 2.** Identified constants with 95% intervals. Intervals are "
          "Monte Carlo (N = 4000) over instrument, property and metering "
          "uncertainties. The `independent recheck` column is a second "
          "identification of the same constant by a different route in "
          "`make_tables.py`; it is a consistency check, not an additional "
          "measurement. Generated by `make_tables.py`.", "",
          "| Quantity | Value | 95% interval | Note | Independent recheck | Source |",
          "|---|---|---|---|---|---|"]
    for _, r in out.iterrows():
        md.append("| " + " | ".join(str(r[c]) for c in out.columns) + " |")
    open(P("table2_identified_constants.md"), "w").write("\n".join(md) + "\n")
    return out


if __name__ == "__main__":
    t1 = table1()
    print(f"table 1: {len(t1)} runs -> table1_campaign_envelope.csv/.md")
    t2 = table2()
    print(f"table 2: {len(t2)} constants -> table2_identified_constants.csv/.md\n")
    print(t2.to_string(index=False))
